### ISSUE TITLE
Missing catalog-info.yaml file

### ISSUE THREAD

**Issue by cmoulliard** [sample-accelerators/spring-petclinic#4]
## Request

Would it be possible to add to this project the following `catalog-info.yaml` file needed by backstage.io (= TAP GUI) to display it within the console of the portal ?

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-petclinic-app
  description: Spring Petclinic App
  tags:
    - app-accelerator
    - java
    - spring-boot
    - web
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-petclinic-app'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
  system: spring-petclinic-app
```
